- hosts: localhost
  tasks:
  - debug:
      msg: "{{ hostvars['node1']['ansible_host'] }}"
  - debug:
      msg: "{{ hostvars[ groups['mgmt'][0] ]['ansible_host'] }}"
  - debug:
      msg: "{{ hostvars[ lookup('inventory_hostnames', 'mgmt') ]['ansible_host'] }}"
