- hosts: mgmt
  become: true
  roles:
  - web

  post_tasks:
  - name: Access Check
    uri:
      url: "http://{{ hostvars[ lookup('inventory_hostnames', 'mgmt') ]['ansible_host'] }}:{{ web_port }}"
      status_code: 200
      return_content: yes
    delegate_to: localhost
