- hosts: localhost
  gather_facts: no

  vars:
    #text_list:
    #  - a
    #  - b
    #  - c
    text_list: ['a', 'b', 'c']
  tasks:
  - debug:
      msg: "{{ item }}"
    with_items: "{{ text_list }}"

